# This file is auto-generated by misc/exports_to_py.py
# DO NOT edit this file manually!
# To regenerate this file, run:
#     python misc/exports_to_py.py

# Enum "TieError"
TIE_ERROR_SUCCESS = 0
TIE_ERROR_INVALID_ARGUMENT = -101
TIE_ERROR_INVALID_RETURN_ARG = -102
TIE_ERROR_INVALID_HANDLE = -103
TIE_ERROR_INVALID_INDEX = -104
TIE_ERROR_TAICHI_TYPE_ERROR = -201
TIE_ERROR_TAICHI_SYNTAX_ERROR = -202
TIE_ERROR_TAICHI_INDEX_ERROR = -203
TIE_ERROR_TAICHI_RUNTIME_ERROR = -204
TIE_ERROR_TAICHI_ASSERTION_ERROR = -205
TIE_ERROR_OUT_OF_MEMORY = -298
TIE_ERROR_UNKNOWN_CXX_EXCEPTION = -299
TIE_ERROR_CALLBACK_FAILED = -301
TIE_ERROR_UNKNOWN = -0x7FFFFFFF
